version: "3"

services:
  web:
    build: .
    ports:
      - "5002:5000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app
      - REDIS_URL=redis://@cache:6379/0
    depends_on:
      - db
      - cache

  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - postgres-data:/var/lib/postgresql/data

  cache:
    image: redis:5
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
