export let places =
    [{
        id: '1',
        position: [48.864716, 2.349],
        title: "My title",
        subtitle: "My subtitle",
        description: "My description",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
    }, {
        id: '2',
        position: [48.854716, 2.349],
        title: "My title 2",
        description: "My description 2",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
    },
        {
            id: '1',
            position: [48.864716, 2.349],
            title: "My title",
            subtitle: "My subtitle",
            description: "My description",
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
        }, {
        id: '2',
        position: [48.854716, 2.349],
        title: "My title 2",
        subtitle: "My subtitle 2",
        description: "My description 2",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
    },
        {
            id: '1',
            position: [48.864716, 2.349],
            title: "My title",
            subtitle: "My subtitle",
            description: "My description",
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
        }, {
        id: '2',
        position: [48.854716, 2.349],
        title: "My title 2",
        subtitle: "My subtitle 2",
        description: "My description 2",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
    },
        {
            id: '1',
            position: [48.864716, 2.349],
            title: "My title",
            subtitle: "My subtitle",
            description: "My description",
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
        }, {
        id: '2',
        position: [48.854716, 2.349],
        title: "My title 2",
        subtitle: "My subtitle 2",
        description: "My description 2",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
    },
        {
            id: '1',
            position: [48.864716, 2.349],
            title: "My title",
            subtitle: "My subtitle",
            description: "My description",
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
        }, {
        id: '2',
        position: [48.854716, 2.349],
        title: "My title 2",
        subtitle: "My subtitle 2",
        description: "My description 2",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
    },
        {
            id: '1',
            position: [48.864716, 2.349],
            title: "My title",
            subtitle: "My subtitle",
            description: "My description",
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
        }, {
        id: '2',
        position: [48.854716, 2.349],
        title: "My title 2",
        subtitle: "My subtitle 2",
        description: "My description 2",
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQHCBAj8nRJkEwjWg5TpNuSZZG9iscsf43V1mfx0LZHNDYW3S_&usqp=CAU',
    }];
